version: '3.8'

services:
  osmhistory:
    image: ghcr.io/${GITHUB_REPOSITORY}-osmhistory:latest
    container_name: osmhistory
    restart: unless-stopped
    ports:
      - "8001:8000"
    volumes:
      - ./data:/app/data
    environment:
      - DB_PATH=/app/data/cache.db
